version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: homebank-report
    tty: true
    working_dir: /app
    volumes:
      - /tmp:/tmp
    command: [
        "poetry",
        "run",
        "python",
        "main.py",
        "/tmp/test.xhb"
    ]
