version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: homebank-report
    tty: true
    working_dir: /app
    volumes:
      - /tmp:/tmp
      - ./:/app
    environment:
      GRAPHS_PATH: "/tmp/graphs"
      XML_FILE: "/tmp/test.xhb"
      NOTIFICATIONS_CONFIG_FILE: "/tmp/notifications_configuration.yml"
    command: [
        "poetry",
        "run",
        "python",
        "main.py"
    ]
